version: "3.3"

services:
  pagger:
    container_name: sms
    build: ./pagger
    ports:
      - 3030:3030
    networks:
      - "monitoring"

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    networks:
      - "monitoring"

  telegraf:
    container_name: telegraf
    image: telegraf:latest
    volumes:
      - "./telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "monitoring"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config:/prometheus
      - ./data/prometheus:/data
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
    ports:
      - 9090:9090
    depends_on:
      - alertmanager
    restart: always
    networks:
      - monitoring 

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./config:/prometheus
      - ./data/alertmanager:/data
    command:
      - '--config.file=/prometheus/alertmanager.yml'
      - '--storage.path=/data'
    ports:
      - 9093:9093
    networks:
      - monitoring 

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning
      - ./grafana/dashboards/:/etc/grafana/dashboards
    depends_on:
      - influxdb
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    networks:
      - monitoring   


volumes:
  influxdb:
  grafana-storage:


networks:
  monitoring: